
spring:
  datasource:
    url: jdbc:mysql://root:coYEbUAtFDPESIVgWDyRUfSRvMUQQmiz@mysql.railway.internal:3306/railway
    username: root
    password: coYEbUAtFDPESIVgWDyRUfSRvMUQQmiz
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Options: none, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
